ci:
  autoupdate_schedule: monthly
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.6
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.12.10
  hooks:
    - id: uv-lock
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.30.0
  hooks:
    - id: zizmor
- repo: https://github.com/thlorenz/doctoc.git
  rev: v2.5.0
  hooks:
    - id: doctoc
      name: Add TOC for Markdown and RST files
      files: README\.md
