ci:
  autoupdate_schedule: monthly
  skip: [pixlet-format]
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.8
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.11.3
  hooks:
    - id: uv-lock
- repo: local
  hooks:
    - id: pixlet-format
      name: Pixlet Format
      entry: pixlet format
      language: system
      types: [text]
      files: '\.star$'
    - id: pixlet-lint
      name: Pixlet Lint
      entry: pixlet lint
      language: system
      types: [text]
      files: '\.star$'
- repo: https://github.com/thlorenz/doctoc.git
  rev: v2.3.0
  hooks:
    - id: doctoc
      name: Add TOC for Markdown and RST files
      files: README\.md
