ci:
  autoupdate_schedule: monthly
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
    - id: ruff
    - id: ruff-format
- repo: local
  hooks:
    - id: pixlet-format
      name: Pixlet Format
      entry: pixlet format
      language: system
      types: [text]
      files: '\.star$'
    - id: pixlet-lint
      name: Pixlet Lint
      entry: pixlet lint
      language: system
      types: [text]
      files: '\.star$'
